### ISSUE TITLE
Dynamsoft.DWT.CreateDWTObject does not call success handler.

### ISSUE THREAD

**Issue by danielson317** [dynamsoft-docs/web-twain-docs#424]
See example on 4.3 of this page: https://www.dynamsoft.com/web-twain/docs/indepth/features/initialize.html and on this page https://github.com/dynamsoft-docs/web-twain-docs/blob/master/indepth/features/initialize.md#dynamsoftdwtcreatedwtobject.

This example when used on a fresh instance with no other code never calls the success handler. Specifically the width/height never change and a `console.log` call inside this same function is never printed to the console.

**Comment by rebeccakak** [comment]
Hi Daniel, did you comment Dynamsoft.DWT.Containers = [{ ContainerId: 'dwtcontrolContainer', Width: 350, Height: 380 }]; this line in the dynamsoft.webtwain.config.js file? If you have any further questions, you can also contact us by email support@dynamsoft.com
